# Generated by Django 4.2.7 on 2023-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('place', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
    ]
